apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: digisense-microservices
  annotations: 
    kubernetes.io/ingress.global-static-ip-name: "admin-portal-cluster01-pubip01"
spec:
  rules:
  - http:
      paths:
        - path: /*
          backend:
            serviceName: digisense-portal-svc
            servicePort: 8001
        - path: /unifiedlogin/*
          backend:
            serviceName: digisense-unifiedlogin-svc
            servicePort: 8001
